### ISSUE TITLE
Can txn read future data?

### ISSUE THREAD

**Issue by crwen** [tonbo-io/tonbo#103]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Rust information: Google your error messages and look at official docs.
- Searched open and closed [GitHub issues](https://github.com/from-the-basement/elsm/issues)

I know txn can not write future data, but can it read future data?
```rust
let txn = db.transaction().await;

let mut txn_future = db.transaction().await;
txn_future.insert("1");
txn_future.commit().await.unwrap();

// can txn get "1" ?
txn.get("1").await.unwrap();
```

**Comment by ethe** [comment]
No, it can't.

**Comment by crwen** [comment]
So the `MergeStream` should add a `read_ts` field, so that it can skip those data with larger timestamps

https://github.com/tonbo-io/tonbo/blob/2e2c9484290c3436f6f04ac88ae3b1e03f42f68e/src/stream/merge.rs#L72-L76

**Comment by ethe** [comment]
Yes, I think so.

**Comment by crwen** [comment]
I'd like to have a try, but I still have one question:

I find `MergeStream` is also used by major compaction, but duplicated keys will be droped when major compaction occurs. This implies that keys may be merged before being queried(especially in long transaction), which may result in reading older version or missing the key

This problem will be more serious after the  implementation of #98

Do you have any good suggestion?
