### ISSUE TITLE
Support OpenDAL

### ISSUE THREAD

**Issue by KKould** [tonbo-io/tonbo#120]
## Feature Request
Since `object-store` support for wasm is weak, currently based on https://github.com/tonbo-io/tonbo/issues/118, it is better to use `opendal` as the implementation.

crates: 
- https://crates.io/crates/parquet_opendal

implementation reference
- https://github.com/tonbo-io/tonbo/pull/113

**Comment by ethe** [comment]
since we started [fusio](https://github.com/tonbo-io/fusio), it is not an enhancement for tonbo any more
