### ISSUE TITLE
Bug: `test::version_log_snap_shot` often errors occur in macos ci 

### ISSUE THREAD

**Issue by KKould** [tonbo-io/tonbo#142]
## Bug Report

manually cycled 30,000 times in window and ubuntu without error, not tested on macos yet

![image](https://github.com/user-attachments/assets/533c556e-8b21-4eea-8c89-75c289cca54a)

**Comment by crwen** [comment]
I think the problem is here: there are more than one log file, and you get wrong log file when list the files.
Maybe you could delete or rename the old log file here:
https://github.com/tonbo-io/tonbo/blob/564fb3f4e99236290fc0127a74e70eeec0f08ca5/src/version/set.rs#L200-L209

**Comment by KKould** [comment]
The strange thing about this problem is that it only occurs in macos. I think it is probably related to `FileProvider::list`, and the existence of multiple logs at the same time is within the scope of the design, because there may be a sudden downtime, choose the second latest one log (this is an overlooked point now, I will improve it now)

**Comment by KKould** [comment]
This problem is mainly caused by the order of the list, and it no longer appears in the new version.
