### ISSUE TITLE
Chore: use `ulid::Generator` replace `Ulid::new`

### ISSUE THREAD

**Issue by KKould** [tonbo-io/tonbo#146]
## Bug Report

ref: https://github.com/tonbo-io/tonbo/pull/145#discussion_r1751540961

**Comment by ClSlaid** [comment]
May I take a look? S'il vous plaît.

**Comment by ClSlaid** [comment]
This can be done by introducing a global FileId generator, and each call to generating a new file id will then *aquire lock* first and then generate.

I wonder if such a way is acceptable for you.
