### ISSUE TITLE
Does it support using datafusion for filter operations?

### ISSUE THREAD

**Issue by loloxwg** [tonbo-io/tonbo#172]
## Question
![CleanShot 2024-09-28 at 14 52 09@2x](https://github.com/user-attachments/assets/5b98649b-0670-49ce-8378-6e4ca98e6728)

**Comment by ethe** [comment]
Yes, I think Tonbo should support predictions pushdown from datafusion, are there any details about this problems?

**Comment by loloxwg** [comment]
The issue arises because tonbo defaults the first column's data type to bool (_null) instead of id (int64). This discrepancy in meta information might be causing inconsistencies within DataFusion.

**Comment by loloxwg** [comment]
![CleanShot 2024-09-28 at 21 44 12@2x](https://github.com/user-attachments/assets/acbc87fb-0a9e-415f-92ea-41e9a1889650)
It seems like the schema information does not include `_null` and `_ts`.

**Comment by ethe** [comment]
It should be fixed.

**Comment by KKould** [comment]
When `DataFusion` executes `BatchCoalescer::finish_batch`, because the schema is the schema of `PlanProperties` obtained from the cache of `MusicExec`, when filter and projection exist at the same time, the schema does not change with the projection, thus causing an index out bound panic.
