### ISSUE TITLE
Add mapping to Rust Bound

### ISSUE THREAD

**Issue by crwen** [tonbo-io/tonbo#182]
Rust `Bound` has three type of value: `Unbounded`, `Included` and `Excluded`, but python can not express them well. So we should build a structure mapping to Rust `Bound` like this:
```py
await txn.scan(Bound::Included(1), Bound::Unbounded, limit=100, projection=["age", "weight"])
```

**Comment by ethe** [comment]
Maybe create a Python standard enum to define `Bound`?

**Comment by crwen** [comment]
> Maybe create a Python standard enum to define `Bound`?

I also have considered two ways:
- use `enum`, but pyo3 does not support the combination of simple enum and complex, so it would look like `Bound::Unbounded()`. Maybe `None` could be used to replace it
- use [generic parameter](https://pyo3.rs/v0.21.2/class#no-generic-parameters) and use `None` to express `Unbounded`

**Comment by crwen** [comment]
ref: #181
