### ISSUE TITLE
Should we bump version to 0.2.0 of this crate?

### ISSUE THREAD

**Issue by doki23** [tonbo-io/tonbo#202]
I've noticed that Tonbo has released version 0.2.0, yet the crate's version remains at 0.1.0. Should we bump it to 0.2.0?

**Comment by doki23** [comment]
The README indicated there would be official support for DataFusion in version 0.2.0, but this was not the case.

**Comment by ethe** [comment]
Yes we will bump to 0.2.0 ASAP, and I am sorry for the delay Datafusion support, please join the discord: https://discord.gg/j27XVFVmJM to get the latest update.

**Comment by ethe** [comment]
I've already bumped tonbo, thanks!
