### ISSUE TITLE
Project layout for `src/tonbo_marco`

### ISSUE THREAD

**Issue by Xuanwo** [tonbo-io/tonbo#50]
## Question

It's surprising to find that `tonbo_marco` is a separate crate yet located inside `src`. This might make it hard to discover and make reader confused. How about move it out?

**Comment by ethe** [comment]
Yes, moving `tonbo_macro` to the top-level should be better

**Comment by ethe** [comment]
Do you have interest to fix it? We are excited to see your contribution 😄

**Comment by Xuanwo** [comment]
Great, I can help to do this.
