### ISSUE TITLE
introduce a new generic attribute macro for tonbo record

### ISSUE THREAD

**Issue by Kilerd** [tonbo-io/tonbo#58]
currently we use a attribute proc macro `primary_key` for the pk field of record struct. (line 3)
```rust
#[tonbo_record]
pub struct User {
    #[primary_key]
    name: String,
    email: Option<String>,
    age: u8,
}
```

I think we should introduce a new one, like `#[record_field]` for defining attributes for fields. and the new attribute `record_field` is not only for primary_key, and also for any kind of field in the struct. the new code may look like:
```rust
#[tonbo_record]
pub struct User {
    #[record_field(primary_key)]
    name: String,
    #[record_field(default_fn="...")]
    email: Option<String>,
    #[record_field(skip)]
    age: u8,
}
```

the idea can make proc macro much more elegant and compatible, cause we can add any params into the attribute `record_field` without any breaking changes.

**Comment by nidnogg** [comment]
I could take this one - could you provide maybe a rundown of how to go about testing this locally?

**Comment by Kilerd** [comment]
Hi @nidnogg,
after digging into the codebase, I find that the macro `tonbo_record` will emit the original struct of the input without any modification, which means this macro is only to append some helper struct and trait implementation for origin struct.

so it can be done by derive proc macro simply. I think there are lots of detail need to be discussed with @ethe .

and for your question about local testing, once the PR #76 is merged, it can be tested easily on local machine.

**Comment by ethe** [comment]
Yes, as I check the usage of macros, I think it could be a derive macro rather than proc macro, this would make implementation cleaner and build faster, I am glad to see someone enhance it.

**Comment by Kilerd** [comment]
hey, @nidnogg do you have any idea of the implementation? or I can work on it.

**Comment by nidnogg** [comment]
I can have a knack at it, I see that pr has gotten merged in

**Comment by nidnogg** [comment]
Hey @Kilerd, so I did come up with an apparently sufficient solution, but I'm currently fiddling a bit with the compiler to get the macro exports to work. I can submit a draft PR soon once I finally clear a few test runs

**Comment by ethe** [comment]
Thanks @nidnogg and @Kilerd, it is completeds since #141 , I hope to have more opportunities collaboration with you guys!
