### ISSUE TITLE
Compile RocksDB only during Benchmark

### ISSUE THREAD

**Issue by KKould** [tonbo-io/tonbo#65]
## Feature Request

now when the test is executed, the compilation of rocksdb will be triggered, which will take a very long time, but rocksdb is only used in the benchmark.

**Comment by ethe** [comment]
I am so sorry I fixed a good first issue just now 😢 https://github.com/tonbo-io/tonbo/commit/67bcd6d34e93c9ed5c6d8b2884713d8b47147b80#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R62
