### ISSUE TITLE
Is the name of the crate `tonbo_marco` a typo?

### ISSUE THREAD

**Issue by Banyc** [tonbo-io/tonbo#73]
## Question

I did the `cargo add tonbo_macros` and it turns out the crate does not exists. 

Naming convention according to popular crates:

- `serde_macros`: <https://crates.io/crates/serde_macros>
- `tokio-macros`: <https://crates.io/crates/tokio-macros>

**Comment by ethe** [comment]
Obviously yes, do you have interest to fix it?

**Comment by Banyc** [comment]
It will take some effort to change the name on crates.io tho. You guys are the only ones authorized to mail them about the change.

**Comment by ethe** [comment]
I will change the crate name if the name is fixed in repository

**Comment by Banyc** [comment]
I'm a bit busy lately

**Comment by ethe** [comment]
Never mind 😄 hope for the collaboration in the future

**Comment by ethe** [comment]
closed in #74
