### ISSUE TITLE
Cargo build failed

### ISSUE THREAD

**Issue by caicancai** [tonbo-io/tonbo#80]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Rust information: Google your error messages and look at official docs.
- Searched open and closed [GitHub issues](https://github.com/from-the-basement/elsm/issues)
![2024-08-17 12-31-20屏幕截图](https://github.com/user-attachments/assets/34058984-5118-4ba6-8f2f-7b15c4039259)
I tried to use MAC and Linux to run cargo build but both failed. Do I need to download any prerequisites?

**Comment by ethe** [comment]
Because Tonbo has MSRV(minimum supported Rust version) required, it was already be specified in main barch, see https://github.com/tonbo-io/tonbo/blob/main/Cargo.toml#L14 , but it is not published to crates.io, it will be published as soon as possible.

**Comment by caicancai** [comment]
> 因为 Tonbo 有 MSRV（最低支持的 Rust 版本）要求，它已经在主 barch 中指定，请参阅https://github.com/tonbo-io/tonbo/blob/main/Cargo.toml#L14，但它尚未发布到 crates.io，这个问题将尽快修复，谢谢 🙏

Thanks

**Comment by caicancai** [comment]
> Because Tonbo has MSRV(minimum supported Rust version) required, it was already be specified in main barch, see https://github.com/tonbo-io/tonbo/blob/main/Cargo.toml#L14 , but it is not published to crates.io, this will be fixed soon as possible, thanks 🙏

Thanks

**Comment by ethe** [comment]
You could manually upgrade rustc above 1.79+ to fixe it temporarily

**Comment by caicancai** [comment]
@ethe 

> You could manually upgrade rustc above 1.79+ to fixe it temporarily

If successful, I will write a document with a brief description to tell subsequent contributors how to build this project until the bug is fixed.

**Comment by caicancai** [comment]
> You could manually upgrade rustc above 1.79+ to fixe it temporarily

Success. Thank you for your reply

**Comment by caicancai** [comment]
@ethe Thank you. I noticed this issue has been fixed
