### ISSUE TITLE
export macro `KeyAttributes` in tonbo lib, and use it in codegen directly

### ISSUE THREAD

**Issue by Kilerd** [tonbo-io/tonbo#94]
https://github.com/tonbo-io/tonbo/pull/85?notification_referrer_id=NT_kwDOADBBC7MxMTk5MTAyMDA2MTozMTYyMzc5#issuecomment-2296519444

currently we use `::tonbo_macro::KeyAttributes` in macro codegen, and it means that user need to add `tonbo_macro` as direct dependency in their project while using, and it's meaningless.

to fix it, 
- [ ] we need to re-export `KeyAttributes` in lib `tonbo` directly like the macro `tonbo_record`
- [ ] update the code of codegen, replace `::tonbo_macro::KeyAttributes` with `::tonbo::KeyAttributes`

**Comment by QuarticCat** [comment]
May I take over this issue?
